wandb_version: 1

name:
  desc: null
  value: seq-cnn-base
data_dir:
  desc: null
  value: /pollard/home/sandyfloren/hierarchical/data/graphreg_data/tfr/
save_dir:
  desc: null
  value: /pollard/home/sandyfloren/hierarchical/bin/graphreg_tf2/weights/seq_cnn_base/
batch_size:
  desc: null
  value: 4
seed:
  desc: null
  value: 62
max_shift:
  desc: null
  value: null
rc_prob:
  desc: null
  value: null
test_time_augment:
  desc: null
  value: false
metric:
  desc: null
  value: null
devices:
  desc: null
  value: 1
accelerator:
  desc: null
  value: gpu
precision:
  desc: null
  value: null
max_epochs:
  desc: null
  value: 100
early_stopping:
  desc: null
  value: false
patience:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.0002
dropout:
  desc: null
  value: 0.5
l2_reg:
  desc: null
  value: 0.0
accumulate_grad_batches:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 1.0e-06
loss_func:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724363768.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
