name: 'seq-cnn-base-lr-0.001'
data_dir: '/pollard/home/sandyfloren/hierarchical/data/graphreg_data/tfr/' 
save_dir:  '/pollard/home/sandyfloren/hierarchical/bin/graphreg_tf2/weights/seq_cnn_base/'
batch_size: 4
seed: 62
max_shift: null
rc_prob: null
test_time_augment: False
metric: null
devices: 1
accelerator: 'gpu'
precision: null
max_epochs: 100
early_stopping: False
patience: 3
learning_rate: 0.001
dropout: 0.5
l2_reg: 0.0
accumulate_grad_batches: null
weight_decay: 0.000001
loss_func: null
