name: 'seq-graphreg'
data_dir: '/pollard/home/sandyfloren/hierarchical/data/graphreg_data/tfr/' 
save_dir:  '/pollard/home/sandyfloren/hierarchical/bin/graphreg_tf2/weights/seq_graphreg/'
seq_cnn_base_model: '/pollard/home/sandyfloren/hierarchical/bin/graphreg_tf2/weights/seq_cnn_base/k562/val_3_13_test_4_14.keras'
batch_size: 4
seed: 62
max_shift: null
rc_prob: null
test_time_augment: False
metric: null
devices: 1
accelerator: 'gpu'
precision: null
max_epochs: 100
early_stopping: True
patience: 5
learning_rate: 0.0002
dropout: 0.5
l2_reg: 0.0
accumulate_grad_batches: null
weight_decay: 0.000001
loss_func: null
